(in-package #:stumpwm-init)

(defcommand terminal() ()
	    (stumpwm:run-or-raise "konsole" '(:class "konsole") ))

(defcommand firefox () ()
  (stumpwm:run-or-raise "firefox"'(:class "Firefox")))
(defcommand pycharm () ()
  (stumpwm:run-or-raise "gtk-launch jetbrains-pycharm-ce"'(:class "jetbrains-pycharm-ce")))
(defcommand idea () ()
  (stumpwm:run-or-raise "gtk-launch jetbrains-idea"'(:class "jetbrains-idea")))
(defcommand slack () ()
  (stumpwm:run-or-raise "slack"'(:class "Slack")))
(defcommand texmacs () ()
  (stumpwm:run-or-raise "texmacs"'(:class "Texmacs.bin")))
(defcommand redshift () ()
  (stumpwm:run-or-raise "redshift"'(:class "redshift")))
