(in-package #:stumpwm-init)

(defcommand terminal() ()
	    (stumpwm:run-or-raise "konsole" '(:class "konsole") ))

(defcommand firefox () ()
  (stumpwm:run-or-raise "firefox"'(:class "Firefox")))
(defcommand pycharm () ()
  (stumpwm:run-or-raise "gtk-launch jetbrains-pycharm-ce"'(:class "jetbrains-pycharm-ce")))
(defcommand idea () ()
  (stumpwm:run-or-raise "gtk-launch jetbrains-idea"'(:class "jetbrains-idea")))
(defcommand slack () ()
  (stumpwm:run-or-raise "slack"'(:class "Slack")))
(defcommand texmacs () ()
  (stumpwm:run-or-raise "texmacs"'(:class "Texmacs.bin")))
(defcommand redshift () ()
  (stumpwm:run-or-raise "redshift-gtk"'(:class "redshift")))

(defun next-window-same-class()
  (setq my-cls-name (stumpwm:window-class (stumpwm:current-window)))
  (defun wm-class-p(cls-name)
    (lambda(w) (equal (stumpwm:window-class w) cls-name)))
  (defun same-wm-class-as-current-window-p(w) (funcall (wm-class-p my-cls-name) w))
  (setq windows (remove-if-not #'same-wm-class-as-current-window-p (stumpwm:group-windows (stumpwm:current-group))))
  (defun current-window-p(w) (eq (stumpwm:window-number w) (stumpwm:window-number (stumpwm:current-window))))
  (setq my-window-index (position-if #'current-window-p windows))
  (setq next-window-index (rem (+ my-window-index 1) (length windows)))
  (stumpwm:select-window-by-number (stumpwm:window-number (nth next-window-index windows)))
  )

(defcommand nextw() ()
  (next-window-same-class))
